### ISSUE TITLE
vlabs-analytics vm is running out of disk space

### ISSUE THREAD

**Issue by ksripathi** [vlead/analytics-db#10]
Hello Shiva/Raghupathi,

I found that vlabs-analytics.vlabs.ac.in vm is running out of disk memory

root@ip-10-100-2-224:~# df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/xvda1       24G   22G  476M  98% /
udev            494M   12K  494M   1% /dev
tmpfs           100M  252K  100M   1% /run
none            5.0M     0  5.0M   0% /run/lock
none            498M     0  498M   0% /run/shm

kindly increase the space

**Comment by sivashankerN** [comment]
@ksripathi , 
I am looking into this, i will let you know once it is done

**Comment by sivashankerN** [comment]
@ksripathi 
Increased disk space to 200 GB.

Please update the command that you are going to use to dump elasticsearch database here

**Comment by ksripathi** [comment]
@sivashankerN

We are no more using current exisitng backup/restore scripts for elasticsearch I am working on new backup/restore scripts which user best practises suggested by elasticsearch community I will update the scripts and let you know once done

**Comment by ksripathi** [comment]
@sivashankerN

Also do you have a documentation on how you increased disk space of AWS EC2 VM to 200GB if so please link here it might useful going forward

**Comment by sivashankerN** [comment]
For any Ubuntu version refer this link : http://issues.vlabs.ac.in/issues/833

For any CentOS version  : http://issues.vlabs.ac.in/issues/1070

**Comment by sivashankerN** [comment]
I will prepare a document for this and I will check in this document into bitbucket as well by today end of the day

**Comment by sivashankerN** [comment]
Steps for resizing EC2 Instance volume are documented here https://bitbucket.org/vlead/systems/src/223b82059fd7f29c0059a5e20d610d5ff1212255/aws-docs/howto.org?at=master&fileviewer=file-view-default

**Comment by ksripathi** [comment]
@sivashankerN 
Thank you
