### ISSUE TITLE
Visualisation of feedback in Kibana 

### ISSUE THREAD

**Issue by ashay-maheshwari** [vlead/analytics-db#3]
Below is given the sample feedback format in json -
```
[
{
"user_id": "Null",
"responses": [
{
"question": {
"name": "Please rate your experience",
"question_type": "radio",
"id": "24"
},
"answers": [
{
"name": "4/10",
"id": "9"
}
],
"id": "27"
},
{
"question": {
"name": "Designation",
"question_type": "radio",
"id": "22"
},
"answers": [
{
"name": "Student",
"id": "1"
}
],
"id": "1"
},
{
"question": {
"name": "Did you attempt any experiments ?",
"question_type": "radio",
"id": "23"
},
"answers": [
{
"name": "No",
"id": "2"
}
],
"id": "10"
},
{
"question": {
"name": "Please provide any other feedback about Virtual Labs",
"question_type": "textarea",
"id": "21"
},
"answers": [
{
"name": "",
"id": "6"
}
],
"id": "12"
}
],
"exp_name": "Null",
"lab_name": "generic feedback",
"version": "generic-feedback-v2.0",
"gateway_ip": "10.100.1.7",
"date": "20-10-2016",
"id": "7"
}
]

```

Each of such feedback must result into some dashboards

**Comment by ashay-maheshwari** [comment]
Creating dashboards in Kibana using Nested Json object inputs is not currently supported. 
Read the following -

- https://discuss.elastic.co/t/kibana-visualizations-over-nested-objects/21996/2
- https://discuss.elastic.co/t/getting-around-kibanas-missing-support-for-nested-objects-parent-child/53529
- http://stackoverflow.com/questions/30648488/nested-object-in-kibana-visualize

Still there are some hints of work around. This needs efforts to identify -
1. If it is directly possible
2. Or need to trick out some way

**Comment by ksripathi** [comment]
Query posted on stack over flow : https://stackoverflow.com/questions/46139022/aggregation-queries-on-nested-objects

**Comment by ksripathi** [comment]
Closing this issue since we are not using visualization tool 'kibana' anymore
