### ISSUE TITLE
Kibana couldn't visualise keywords  having special charecter "-"

### ISSUE THREAD

**Issue by mrudhvika940** [vlead/analytics-db#5]
`{
  "user_id": "Null",
  "Please rate your experience": "4/10",
  "Designation": "Student",
  "Did you attempt any experiments ": "No",
  "Please provide any other feedback about Virtual Labs": "good",
  "exp_name": "Null",
  "lab_name": "generic feedback",
  "version": "generic-feedback-v2.0",
  "gateway_ip": "10.100.1.7",
  "date": "20-10-2016",
  "id": "1"
}`
While trying to generating a graph by posting the above json. the result obtained for key value **version** is it considered **generic**, **feedback** and **v2.0** as three values instead of taking as one value

**Comment by ksripathi** [comment]
Since we are not using Kibana visualization tool anymore i am closing this issue
