### ISSUE TITLE
Making elasticsearch service ADS deployable

### ISSUE THREAD

**Issue by mrudhvika940** [vlead/analytics-db#8]
Elasticsearch service should be deployable using ADS service also backup/restore scripts should be written

**Comment by ksripathi** [comment]
During ADS deployment while installing java8 on container it is taking too long time (command can be found at #13)

Hence we can create openvz template with java8 installed

**Comment by ksripathi** [comment]
Updated required things to make it auto deployable 
deploy spec can be found at : https://github.com/vlead/analytics-db/blob/refactor/scripts/labspec.json
