### ISSUE TITLE
Backup and restore scripts to be written for elastic search

### ISSUE THREAD

**Issue by mrudhvika940** [vlead/analytics-db#9]
This issue captures documentation to backup all the indexes in elastic search database and restore the same

**Comment by ksripathi** [comment]
Refer : https://stackoverflow.com/questions/38346678/backup-and-restore-elasticsearch-elasticdump

**Comment by ksripathi** [comment]
Refer : https://jee-appy.blogspot.in/2016/11/elasticsearch-backup-and-restore.html

**Comment by ksripathi** [comment]
@mrudhvika940 

I am almost done with this task kindly work on #8

**Comment by ksripathi** [comment]
Current existing backup script is using elasticdump utility refer 

There are REST APIs provided by elasticsearch service to take regular snapshots and restore the same this approach is more intelligent than elasticdump utility

Reference : https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-snapshots.html#modules-snapshots

**Comment by ksripathi** [comment]
Backup script can be found at : https://github.com/vlead/analytics-db/blob/refactor/scripts/backup

**Comment by ksripathi** [comment]
Restore script can be found at : https://github.com/vlead/analytics-db/blob/refactor/scripts/restore
